import type {
  ActivityItem,
  AssessmentQuestion,
  Control,
  Framework,
  Incident,
  Notification,
  Risk,
  Vendor,
} from "./types";
import { classifyRisk } from "./utils";

export const ORG = {
  name: "Apex Technologies Ltd.",
  industry: "Technology & Digital Services",
  employees: 1250,
  locations: ["India", "UAE", "Singapore"],
};

export const DEMO_USER = {
  name: "Sarah Mathew",
  role: "Risk & Compliance Manager",
  initials: "SM",
};

const r = (
  partial: Omit<
    Risk,
    | "level"
    | "treatmentPlan"
    | "timeline"
    | "linkedControls"
    | "linkedVendors"
    | "linkedIncidents"
    | "residualLikelihood"
    | "residualImpact"
    | "appetite"
  > &
    Partial<Risk>,
): Risk => ({
  residualLikelihood: Math.max(1, partial.likelihood - 1),
  residualImpact: partial.impact,
  appetite: "Within tolerance once residual score is below 10",
  treatmentPlan: [],
  timeline: [
    {
      id: `${partial.id}-t1`,
      date: partial.dateIdentified,
      title: "Risk created",
      actor: "Sarah Mathew",
    },
    {
      id: `${partial.id}-t2`,
      date: partial.dateIdentified,
      title: "Owner assigned",
      detail: `Assigned to ${partial.owner}`,
      actor: "Sarah Mathew",
    },
    {
      id: `${partial.id}-t3`,
      date: partial.lastReviewed,
      title: "Review completed",
      actor: partial.owner,
    },
  ],
  linkedControls: [],
  linkedVendors: [],
  linkedIncidents: [],
  ...partial,
  level: classifyRisk(partial.likelihood * partial.impact),
});

export const SEED_RISKS: Risk[] = [
  r({
    id: "RISK-001",
    title: "Ransomware attack on production systems",
    description:
      "A ransomware attack could encrypt production workloads and customer-facing services, causing extended downtime, data loss and contractual penalties across the India and Singapore delivery centres.",
    category: "Cybersecurity",
    department: "IT",
    owner: "Arjun Nair",
    likelihood: 4,
    impact: 5,
    residualLikelihood: 2,
    residualImpact: 4,
    treatment: "Mitigate",
    treatmentOwner: "Rahul Menon",
    status: "In Progress",
    dateIdentified: "2026-03-14",
    lastReviewed: "2026-09-02",
    reviewDate: "2026-10-15",
    appetite: "Residual score must be reduced below 10 by Q4 2026",
    treatmentPlan: [
      { id: "ta-1", title: "Implement endpoint detection and response", owner: "Rahul Menon", dueDate: "2026-10-10", status: "In Progress" },
      { id: "ta-2", title: "Enable immutable backups for production data", owner: "Arjun Nair", dueDate: "2026-10-30", status: "In Progress" },
      { id: "ta-3", title: "Conduct phishing simulation for all staff", owner: "Priya Sharma", dueDate: "2026-11-15", status: "Not Started" },
      { id: "ta-4", title: "Review disaster recovery process", owner: "Arjun Nair", dueDate: "2026-11-30", status: "Not Started" },
    ],
    timeline: [
      { id: "r1-t1", date: "2026-03-14", title: "Risk created", actor: "Sarah Mathew" },
      { id: "r1-t2", date: "2026-03-15", title: "Owner assigned", detail: "Assigned to Arjun Nair", actor: "Sarah Mathew" },
      { id: "r1-t3", date: "2026-04-02", title: "Assessment completed", detail: "Inherent score 20 (Critical)", actor: "Arjun Nair" },
      { id: "r1-t4", date: "2026-05-20", title: "Treatment plan added", detail: "4 mitigation actions defined", actor: "Rahul Menon" },
      { id: "r1-t5", date: "2026-09-02", title: "Review completed", detail: "EDR rollout at 70% of endpoints", actor: "Arjun Nair" },
    ],
    linkedControls: ["A.8.7", "A.8.13"],
    linkedVendors: ["cloudnova"],
    linkedIncidents: ["INC-009"],
  }),
  r({
    id: "RISK-002",
    title: "Loss of key supplier for managed network services",
    description:
      "Failure or exit of the primary managed network services supplier would disrupt connectivity across all three locations and delay client deliverables.",
    category: "Operational",
    department: "Procurement",
    owner: "Divya Krishnan",
    likelihood: 3,
    impact: 4,
    treatment: "Mitigate",
    treatmentOwner: "Divya Krishnan",
    status: "Open",
    dateIdentified: "2026-04-08",
    lastReviewed: "2026-08-18",
    reviewDate: "2026-11-01",
    treatmentPlan: [
      { id: "ta-5", title: "Qualify secondary network supplier", owner: "Divya Krishnan", dueDate: "2026-11-20", status: "In Progress" },
      { id: "ta-6", title: "Negotiate exit-assistance clause in renewal", owner: "Legal Team", dueDate: "2026-12-05", status: "Not Started" },
    ],
    linkedControls: ["A.5.19"],
    linkedVendors: ["nexus"],
  }),
  r({
    id: "RISK-003",
    title: "Customer data privacy violation",
    description:
      "Mishandling of customer personal data during support operations could breach GDPR and local data protection laws, resulting in fines and reputational damage.",
    category: "Compliance",
    department: "Legal & Compliance",
    owner: "Meera Iyer",
    likelihood: 2,
    impact: 5,
    treatment: "Mitigate",
    treatmentOwner: "Meera Iyer",
    status: "In Progress",
    dateIdentified: "2026-02-20",
    lastReviewed: "2026-08-30",
    reviewDate: "2026-10-20",
    treatmentPlan: [
      { id: "ta-7", title: "Roll out data handling training for support staff", owner: "Priya Sharma", dueDate: "2026-10-25", status: "In Progress" },
      { id: "ta-8", title: "Deploy DLP policy for customer data exports", owner: "Rahul Menon", dueDate: "2026-11-10", status: "Not Started" },
    ],
    linkedControls: ["A.8.12", "GDPR-5"],
    linkedIncidents: ["INC-013"],
  }),
  r({
    id: "RISK-004",
    title: "Cloud platform single-region failure",
    description:
      "Core SaaS workloads are concentrated in a single cloud region. A regional outage would breach availability SLAs for 40+ enterprise customers.",
    category: "Business Continuity",
    department: "Engineering",
    owner: "Vikram Rao",
    likelihood: 4,
    impact: 4,
    treatment: "Mitigate",
    treatmentOwner: "Vikram Rao",
    status: "In Progress",
    dateIdentified: "2026-01-12",
    lastReviewed: "2026-09-05",
    reviewDate: "2026-10-05",
    treatmentPlan: [
      { id: "ta-9", title: "Design multi-region failover architecture", owner: "Vikram Rao", dueDate: "2026-11-30", status: "In Progress" },
      { id: "ta-10", title: "Run regional failover test", owner: "DevOps", dueDate: "2026-12-15", status: "Not Started" },
    ],
    linkedControls: ["A.8.13", "NIST-RC1"],
    linkedVendors: ["cloudnova"],
    linkedIncidents: ["INC-012"],
  }),
  r({
    id: "RISK-005",
    title: "Phishing-led credential compromise",
    description:
      "Targeted phishing campaigns could compromise employee credentials and provide initial access to corporate systems.",
    category: "Cybersecurity",
    department: "IT Security",
    owner: "Rahul Menon",
    likelihood: 4,
    impact: 3,
    treatment: "Mitigate",
    treatmentOwner: "Rahul Menon",
    status: "In Progress",
    dateIdentified: "2026-03-02",
    lastReviewed: "2026-08-25",
    reviewDate: "2026-11-15",
    linkedControls: ["A.6.3", "SOC2-CC6"],
    linkedIncidents: ["INC-010"],
  }),
  r({
    id: "RISK-006",
    title: "Legacy ERP approaching end of vendor support",
    description:
      "The finance ERP reaches end of extended support in 2027, increasing the likelihood of unpatched vulnerabilities and operational failures.",
    category: "Operational",
    department: "Finance",
    owner: "Daniel Fernandez",
    likelihood: 3,
    impact: 3,
    treatment: "Mitigate",
    treatmentOwner: "Daniel Fernandez",
    status: "Open",
    dateIdentified: "2026-05-11",
    lastReviewed: "2026-08-11",
    reviewDate: "2026-11-11",
  }),
  r({
    id: "RISK-007",
    title: "Insider threat – privileged data exfiltration",
    description:
      "A privileged insider could exfiltrate sensitive customer or intellectual property data. Monitoring coverage of privileged sessions is currently partial.",
    category: "Cybersecurity",
    department: "IT Security",
    owner: "Rahul Menon",
    likelihood: 4,
    impact: 4,
    treatment: "Mitigate",
    treatmentOwner: "Rahul Menon",
    status: "Open",
    dateIdentified: "2026-06-01",
    lastReviewed: "2026-09-01",
    reviewDate: "2026-10-01",
    treatmentPlan: [
      { id: "ta-11", title: "Extend session recording to all privileged accounts", owner: "Rahul Menon", dueDate: "2026-10-20", status: "In Progress" },
      { id: "ta-12", title: "Quarterly privileged access review", owner: "Arjun Nair", dueDate: "2026-10-31", status: "Not Started" },
    ],
    linkedControls: ["A.8.2", "A.8.16"],
    linkedIncidents: ["INC-014"],
  }),
  r({
    id: "RISK-008",
    title: "Payment fraud in accounts payable process",
    description:
      "Weak verification of supplier bank detail changes could enable invoice redirection fraud.",
    category: "Financial",
    department: "Finance",
    owner: "Daniel Fernandez",
    likelihood: 3,
    impact: 4,
    treatment: "Mitigate",
    treatmentOwner: "Daniel Fernandez",
    status: "In Progress",
    dateIdentified: "2026-04-22",
    lastReviewed: "2026-08-22",
    reviewDate: "2026-11-22",
    linkedVendors: ["securepay"],
  }),
  r({
    id: "RISK-009",
    title: "Foreign exchange volatility across INR, AED and SGD",
    description:
      "Revenue and cost bases span three currencies. Sustained volatility could compress margins on fixed-price contracts.",
    category: "Financial",
    department: "Finance",
    owner: "Daniel Fernandez",
    likelihood: 3,
    impact: 3,
    treatment: "Accept",
    treatmentOwner: "Daniel Fernandez",
    status: "Open",
    dateIdentified: "2026-02-05",
    lastReviewed: "2026-08-05",
    reviewDate: "2027-02-05",
  }),
  r({
    id: "RISK-010",
    title: "Vendor concentration in cloud infrastructure",
    description:
      "Heavy dependence on a single cloud infrastructure vendor creates commercial and continuity exposure.",
    category: "Third Party",
    department: "IT",
    owner: "Arjun Nair",
    likelihood: 3,
    impact: 4,
    treatment: "Transfer",
    treatmentOwner: "Divya Krishnan",
    status: "Open",
    dateIdentified: "2026-05-30",
    lastReviewed: "2026-08-28",
    reviewDate: "2026-11-28",
    linkedVendors: ["cloudnova", "meridian"],
  }),
  r({
    id: "RISK-011",
    title: "Shadow IT adoption of unapproved SaaS tools",
    description:
      "Teams procuring SaaS tools outside the approval process create unmanaged data flows and licence exposure.",
    category: "Cybersecurity",
    department: "IT",
    owner: "Arjun Nair",
    likelihood: 3,
    impact: 2,
    treatment: "Mitigate",
    treatmentOwner: "Arjun Nair",
    status: "Open",
    dateIdentified: "2026-06-15",
    lastReviewed: "2026-09-10",
    reviewDate: "2026-12-10",
  }),
  r({
    id: "RISK-012",
    title: "Regulatory penalty for data localisation non-compliance",
    description:
      "New data localisation requirements in India may not be fully met by current data residency architecture, exposing the organisation to regulatory action.",
    category: "Compliance",
    department: "Legal & Compliance",
    owner: "Meera Iyer",
    likelihood: 4,
    impact: 4,
    treatment: "Mitigate",
    treatmentOwner: "Meera Iyer",
    status: "Open",
    dateIdentified: "2026-07-01",
    lastReviewed: "2026-09-08",
    reviewDate: "2026-10-08",
    treatmentPlan: [
      { id: "ta-13", title: "Complete data residency gap assessment", owner: "Meera Iyer", dueDate: "2026-10-15", status: "In Progress" },
      { id: "ta-14", title: "Migrate in-scope datasets to Indian region", owner: "Vikram Rao", dueDate: "2026-12-20", status: "Not Started" },
    ],
    linkedControls: ["GDPR-3"],
  }),
  r({
    id: "RISK-013",
    title: "Physical access control gaps at Singapore office",
    description:
      "Tailgating and visitor management gaps were observed during the last physical security walkthrough of the Singapore office.",
    category: "Operational",
    department: "Facilities",
    owner: "Wei Ling Tan",
    likelihood: 2,
    impact: 3,
    treatment: "Mitigate",
    treatmentOwner: "Wei Ling Tan",
    status: "In Progress",
    dateIdentified: "2026-06-20",
    lastReviewed: "2026-08-20",
    reviewDate: "2026-11-20",
    linkedControls: ["A.7.2", "A.7.4"],
  }),
  r({
    id: "RISK-014",
    title: "Attrition of key security engineering talent",
    description:
      "Loss of senior security engineers would delay the control improvement roadmap and increase reliance on external providers.",
    category: "Strategic",
    department: "HR",
    owner: "Priya Sharma",
    likelihood: 3,
    impact: 4,
    treatment: "Mitigate",
    treatmentOwner: "Priya Sharma",
    status: "Open",
    dateIdentified: "2026-05-05",
    lastReviewed: "2026-08-05",
    reviewDate: "2026-11-05",
  }),
  r({
    id: "RISK-015",
    title: "Third-party support SLA breaches",
    description:
      "Recurring SLA breaches by the outsourced customer support provider are degrading customer satisfaction scores.",
    category: "Third Party",
    department: "Operations",
    owner: "Divya Krishnan",
    likelihood: 3,
    impact: 3,
    treatment: "Mitigate",
    treatmentOwner: "Divya Krishnan",
    status: "In Progress",
    dateIdentified: "2026-07-10",
    lastReviewed: "2026-09-10",
    reviewDate: "2026-12-10",
    linkedVendors: ["nexus"],
    linkedIncidents: ["INC-008"],
  }),
  r({
    id: "RISK-016",
    title: "GDPR data subject request backlog",
    description:
      "Data subject access requests are trending above the 30-day statutory response window during peak periods.",
    category: "Data Privacy",
    department: "Legal & Compliance",
    owner: "Meera Iyer",
    likelihood: 2,
    impact: 5,
    treatment: "Mitigate",
    treatmentOwner: "Meera Iyer",
    status: "Open",
    dateIdentified: "2026-08-01",
    lastReviewed: "2026-09-01",
    reviewDate: "2026-11-01",
    linkedControls: ["GDPR-2"],
  }),
  r({
    id: "RISK-017",
    title: "Inadequate business continuity plan testing cadence",
    description:
      "BCP exercises have not been run for two critical business services in the last 12 months.",
    category: "Business Continuity",
    department: "Operations",
    owner: "Vikram Rao",
    likelihood: 2,
    impact: 4,
    treatment: "Mitigate",
    treatmentOwner: "Vikram Rao",
    status: "Open",
    dateIdentified: "2026-06-25",
    lastReviewed: "2026-08-25",
    reviewDate: "2026-11-25",
    linkedControls: ["NIST-RC1"],
  }),
  r({
    id: "RISK-018",
    title: "Regulatory uncertainty in UAE market expansion",
    description:
      "Evolving licensing requirements for digital services in the UAE could delay the planned market expansion.",
    category: "Strategic",
    department: "Legal & Compliance",
    owner: "Ahmed Al Farsi",
    likelihood: 2,
    impact: 4,
    treatment: "Accept",
    treatmentOwner: "Ahmed Al Farsi",
    status: "Open",
    dateIdentified: "2026-04-18",
    lastReviewed: "2026-08-18",
    reviewDate: "2027-01-18",
  }),
  r({
    id: "RISK-019",
    title: "Data retention policy gaps in legacy archives",
    description:
      "Legacy archives contain customer data beyond defined retention periods, increasing privacy and discovery exposure.",
    category: "Data Privacy",
    department: "IT",
    owner: "Arjun Nair",
    likelihood: 3,
    impact: 2,
    treatment: "Mitigate",
    treatmentOwner: "Arjun Nair",
    status: "Open",
    dateIdentified: "2026-07-22",
    lastReviewed: "2026-09-05",
    reviewDate: "2026-12-05",
    linkedVendors: ["datavault"],
  }),
  r({
    id: "RISK-020",
    title: "Delays in endpoint security patching",
    description:
      "Patch deployment for remote endpoints regularly exceeds the 14-day internal standard, extending the vulnerability window.",
    category: "Cybersecurity",
    department: "IT",
    owner: "Arjun Nair",
    likelihood: 3,
    impact: 3,
    treatment: "Mitigate",
    treatmentOwner: "Arjun Nair",
    status: "In Progress",
    dateIdentified: "2026-05-19",
    lastReviewed: "2026-09-03",
    reviewDate: "2026-11-03",
  }),
  r({
    id: "RISK-021",
    title: "Travel disruption impacting client delivery",
    description:
      "Regional travel disruption could delay on-site client engagements in the UAE and Singapore.",
    category: "Operational",
    department: "Operations",
    owner: "Wei Ling Tan",
    likelihood: 2,
    impact: 2,
    treatment: "Accept",
    treatmentOwner: "Wei Ling Tan",
    status: "Open",
    dateIdentified: "2026-03-30",
    lastReviewed: "2026-08-30",
    reviewDate: "2027-02-28",
  }),
  r({
    id: "RISK-022",
    title: "Improper disposal of storage media and peripherals",
    description:
      "End-of-life devices are not consistently sanitised before disposal, creating a residual data exposure risk.",
    category: "Data Privacy",
    department: "IT",
    owner: "Arjun Nair",
    likelihood: 1,
    impact: 3,
    treatment: "Mitigate",
    treatmentOwner: "Arjun Nair",
    status: "Open",
    dateIdentified: "2026-06-08",
    lastReviewed: "2026-09-08",
    reviewDate: "2026-12-08",
    linkedControls: ["A.7.10"],
  }),
  r({
    id: "RISK-023",
    title: "Brand impersonation and domain spoofing",
    description:
      "Fraudulent domains imitating the Apex Technologies brand could be used for phishing customers and partners.",
    category: "Cybersecurity",
    department: "IT Security",
    owner: "Rahul Menon",
    likelihood: 2,
    impact: 2,
    treatment: "Mitigate",
    treatmentOwner: "Rahul Menon",
    status: "Under Review",
    dateIdentified: "2026-08-12",
    lastReviewed: "2026-09-12",
    reviewDate: "2026-10-12",
  }),
  r({
    id: "RISK-024",
    title: "Minor workplace safety findings at Bengaluru office",
    description:
      "The annual facilities inspection identified minor fire-safety signage and evacuation drill gaps.",
    category: "Compliance",
    department: "Facilities",
    owner: "Wei Ling Tan",
    likelihood: 1,
    impact: 3,
    treatment: "Mitigate",
    treatmentOwner: "Wei Ling Tan",
    status: "In Progress",
    dateIdentified: "2026-07-15",
    lastReviewed: "2026-09-01",
    reviewDate: "2026-12-01",
  }),
];

export const FRAMEWORKS: Framework[] = [
  {
    id: "iso-27001",
    name: "ISO/IEC 27001:2022",
    shortName: "ISO 27001",
    description: "Information security management system controls (Annex A).",
    areas: ["Organisational Controls", "People Controls", "Physical Controls", "Technological Controls"],
  },
  {
    id: "soc-2",
    name: "SOC 2 Type II",
    shortName: "SOC 2",
    description: "Trust Services Criteria for security, availability and confidentiality.",
    areas: ["Common Criteria", "Availability", "Confidentiality"],
  },
  {
    id: "gdpr",
    name: "EU General Data Protection Regulation",
    shortName: "GDPR",
    description: "Data protection obligations for personal data of EU data subjects.",
    areas: ["Lawfulness & Transparency", "Data Subject Rights", "Security of Processing", "Accountability"],
  },
  {
    id: "nist-csf",
    name: "NIST Cybersecurity Framework 2.0",
    shortName: "NIST CSF",
    description: "Cybersecurity outcomes across Govern, Identify, Protect, Detect, Respond and Recover.",
    areas: ["Govern", "Identify", "Protect", "Detect", "Respond", "Recover"],
  },
];

const c = (
  partial: Omit<Control, "evidence" | "notes" | "lastReviewed" | "nextReview"> &
    Partial<Control>,
): Control => ({
  evidence: [],
  notes: [],
  lastReviewed: "2026-08-15",
  nextReview: "2027-02-15",
  ...partial,
});

export const SEED_CONTROLS: Control[] = [
  // ISO 27001
  c({
    id: "A.5.1",
    frameworkId: "iso-27001",
    area: "Organisational Controls",
    title: "Policies for Information Security",
    description: "An information security policy and topic-specific policies shall be defined, approved by management, published and reviewed at planned intervals.",
    owner: "Security Team",
    status: "Compliant",
    evidence: [
      { name: "Information-Security-Policy.pdf", uploadedBy: "Rahul Menon", date: "2026-07-02" },
      { name: "Policy-Review-Minutes-2026.pdf", uploadedBy: "Sarah Mathew", date: "2026-07-10" },
    ],
    notes: ["Annual review completed July 2026. No major changes required."],
  }),
  c({
    id: "A.5.15",
    frameworkId: "iso-27001",
    area: "Organisational Controls",
    title: "Access Control",
    description: "Rules to control physical and logical access to information and associated assets shall be established and implemented.",
    owner: "IT",
    status: "Partial",
    evidence: [{ name: "Access-Control-Review.xlsx", uploadedBy: "Arjun Nair", date: "2026-06-18" }],
    notes: ["Access review complete for core systems; SaaS application coverage still in progress."],
  }),
  c({
    id: "A.5.19",
    frameworkId: "iso-27001",
    area: "Organisational Controls",
    title: "Information Security in Supplier Relationships",
    description: "Processes shall be defined to manage information security risks associated with the use of supplier products and services.",
    owner: "Procurement",
    status: "Compliant",
    evidence: [{ name: "Supplier-Security-Standard.pdf", uploadedBy: "Divya Krishnan", date: "2026-05-22" }],
  }),
  c({
    id: "A.5.24",
    frameworkId: "iso-27001",
    area: "Organisational Controls",
    title: "Incident Management Planning and Preparation",
    description: "Incident management shall be planned and prepared by defining processes, roles and responsibilities.",
    owner: "Security Operations",
    status: "Compliant",
    evidence: [{ name: "Incident-Response-Plan-v3.pdf", uploadedBy: "Rahul Menon", date: "2026-04-30" }],
  }),
  c({
    id: "A.5.34",
    frameworkId: "iso-27001",
    area: "Organisational Controls",
    title: "Privacy and Protection of PII",
    description: "Requirements regarding the preservation of privacy and protection of PII shall be identified and met.",
    owner: "Legal & Compliance",
    status: "Compliant",
    evidence: [{ name: "PII-Handling-Standard.pdf", uploadedBy: "Meera Iyer", date: "2026-06-05" }],
  }),
  c({
    id: "A.6.1",
    frameworkId: "iso-27001",
    area: "People Controls",
    title: "Screening",
    description: "Background verification checks on candidates shall be carried out prior to joining and on an ongoing basis.",
    owner: "HR",
    status: "Compliant",
    evidence: [{ name: "Background-Check-Procedure.pdf", uploadedBy: "Priya Sharma", date: "2026-03-11" }],
  }),
  c({
    id: "A.6.3",
    frameworkId: "iso-27001",
    area: "People Controls",
    title: "Information Security Awareness and Training",
    description: "Personnel shall receive appropriate security awareness education, training and regular updates.",
    owner: "HR",
    status: "Compliant",
    evidence: [{ name: "Security-Awareness-Completion-Q3.xlsx", uploadedBy: "Priya Sharma", date: "2026-09-01" }],
    notes: ["96% completion rate for Q3 awareness campaign."],
  }),
  c({
    id: "A.6.5",
    frameworkId: "iso-27001",
    area: "People Controls",
    title: "Responsibilities after Termination or Change of Employment",
    description: "Security responsibilities that remain valid after termination or change of employment shall be defined and enforced.",
    owner: "HR",
    status: "Compliant",
  }),
  c({
    id: "A.7.2",
    frameworkId: "iso-27001",
    area: "Physical Controls",
    title: "Physical Entry",
    description: "Secure areas shall be protected by appropriate entry controls and access points.",
    owner: "Facilities",
    status: "Compliant",
    evidence: [{ name: "Badge-Access-Audit-Aug.xlsx", uploadedBy: "Wei Ling Tan", date: "2026-08-20" }],
  }),
  c({
    id: "A.7.4",
    frameworkId: "iso-27001",
    area: "Physical Controls",
    title: "Physical Security Monitoring",
    description: "Premises shall be continuously monitored for unauthorised physical access.",
    owner: "Facilities",
    status: "Compliant",
  }),
  c({
    id: "A.7.10",
    frameworkId: "iso-27001",
    area: "Physical Controls",
    title: "Storage Media",
    description: "Storage media shall be managed through their life cycle of acquisition, use, transportation and disposal.",
    owner: "IT",
    status: "Compliant",
    notes: ["Certified destruction vendor engaged for end-of-life media."],
  }),
  c({
    id: "A.8.2",
    frameworkId: "iso-27001",
    area: "Technological Controls",
    title: "Privileged Access Rights",
    description: "The allocation and use of privileged access rights shall be restricted and managed.",
    owner: "IT",
    status: "Compliant",
    evidence: [{ name: "Privileged-Access-Register.xlsx", uploadedBy: "Arjun Nair", date: "2026-07-25" }],
  }),
  c({
    id: "A.8.7",
    frameworkId: "iso-27001",
    area: "Technological Controls",
    title: "Protection Against Malware",
    description: "Protection against malware shall be implemented and supported by appropriate user awareness.",
    owner: "Security",
    status: "Compliant",
    evidence: [{ name: "EDR-Coverage-Report.pdf", uploadedBy: "Rahul Menon", date: "2026-08-28" }],
  }),
  c({
    id: "A.8.12",
    frameworkId: "iso-27001",
    area: "Technological Controls",
    title: "Data Leakage Prevention",
    description: "Data leakage prevention measures shall be applied to systems, networks and devices that process, store or transmit sensitive information.",
    owner: "Security",
    status: "Non-Compliant",
    notes: ["DLP tooling selected; deployment scheduled for Q4 2026. Evidence pending."],
  }),
  c({
    id: "A.8.13",
    frameworkId: "iso-27001",
    area: "Technological Controls",
    title: "Information Backup",
    description: "Backup copies of information, software and systems shall be maintained and regularly tested.",
    owner: "IT",
    status: "Compliant",
    evidence: [
      { name: "Backup-Restore-Test-Q2.pdf", uploadedBy: "Arjun Nair", date: "2026-06-30" },
      { name: "Security-Audit-Q3.pdf", uploadedBy: "Sarah Mathew", date: "2026-09-05" },
    ],
  }),
  c({
    id: "A.8.16",
    frameworkId: "iso-27001",
    area: "Technological Controls",
    title: "Monitoring Activities",
    description: "Networks, systems and applications shall be monitored for anomalous behaviour and appropriate actions taken.",
    owner: "Security Operations",
    status: "Partial",
    notes: ["SIEM coverage complete for production; corporate SaaS log sources being onboarded."],
  }),
  c({
    id: "A.8.24",
    frameworkId: "iso-27001",
    area: "Technological Controls",
    title: "Use of Cryptography",
    description: "Rules for the effective use of cryptography, including key management, shall be defined and implemented.",
    owner: "Security",
    status: "Compliant",
  }),
  // SOC 2
  c({ id: "SOC2-CC1", frameworkId: "soc-2", area: "Common Criteria", title: "Control Environment", description: "The entity demonstrates commitment to integrity and ethical values.", owner: "Legal & Compliance", status: "Compliant" }),
  c({ id: "SOC2-CC2", frameworkId: "soc-2", area: "Common Criteria", title: "Communication and Information", description: "The entity communicates security objectives and responsibilities internally and externally.", owner: "Security Team", status: "Compliant" }),
  c({ id: "SOC2-CC3", frameworkId: "soc-2", area: "Common Criteria", title: "Risk Assessment", description: "The entity identifies and assesses risks to the achievement of its objectives.", owner: "Risk Team", status: "Compliant" }),
  c({ id: "SOC2-CC4", frameworkId: "soc-2", area: "Common Criteria", title: "Monitoring of Controls", description: "The entity evaluates and communicates internal control deficiencies in a timely manner.", owner: "Security Operations", status: "Partial", notes: ["Continuous control monitoring tooling under evaluation."] }),
  c({ id: "SOC2-CC5", frameworkId: "soc-2", area: "Common Criteria", title: "Control Activities", description: "The entity deploys control activities through policies and procedures.", owner: "Security Team", status: "Compliant" }),
  c({ id: "SOC2-CC6", frameworkId: "soc-2", area: "Common Criteria", title: "Logical and Physical Access Controls", description: "The entity restricts logical and physical access to authorised users.", owner: "IT", status: "Compliant" }),
  c({ id: "SOC2-CC7", frameworkId: "soc-2", area: "Common Criteria", title: "System Operations", description: "The entity monitors system components for anomalies indicative of malicious acts or errors.", owner: "Security Operations", status: "Non-Compliant", notes: ["Anomaly detection baseline not yet established for new data platform."] }),
  c({ id: "SOC2-CC8", frameworkId: "soc-2", area: "Common Criteria", title: "Change Management", description: "The entity authorises, designs, tests and implements changes to infrastructure and software.", owner: "Engineering", status: "Compliant" }),
  c({ id: "SOC2-A1", frameworkId: "soc-2", area: "Availability", title: "Availability Commitments", description: "The entity maintains and tests capacity, backup and recovery mechanisms to meet availability commitments.", owner: "Engineering", status: "Non-Compliant", notes: ["Multi-region failover programme in progress (see RISK-004)."] }),
  c({ id: "SOC2-C1", frameworkId: "soc-2", area: "Confidentiality", title: "Confidential Information Handling", description: "The entity identifies, protects and disposes of confidential information to meet its objectives.", owner: "Security Team", status: "Compliant" }),
  // GDPR
  c({ id: "GDPR-1", frameworkId: "gdpr", area: "Lawfulness & Transparency", title: "Lawful Basis and Privacy Notices", description: "Processing has a documented lawful basis and data subjects are informed through clear privacy notices.", owner: "Legal & Compliance", status: "Compliant" }),
  c({ id: "GDPR-2", frameworkId: "gdpr", area: "Data Subject Rights", title: "Data Subject Request Handling", description: "Processes exist to respond to access, rectification, erasure and portability requests within statutory timelines.", owner: "Legal & Compliance", status: "Partial", notes: ["Peak-period backlog identified (see RISK-016). Additional automation planned."] }),
  c({ id: "GDPR-3", frameworkId: "gdpr", area: "Accountability", title: "Records of Processing Activities", description: "A register of processing activities is maintained and reviewed regularly.", owner: "Legal & Compliance", status: "Compliant" }),
  c({ id: "GDPR-4", frameworkId: "gdpr", area: "Security of Processing", title: "Technical and Organisational Measures", description: "Appropriate technical and organisational measures protect personal data against unauthorised processing.", owner: "Security Team", status: "Compliant" }),
  c({ id: "GDPR-5", frameworkId: "gdpr", area: "Security of Processing", title: "Personal Data Breach Response", description: "Personal data breaches are detected, reported and documented, including notification within 72 hours where required.", owner: "Security Operations", status: "Compliant" }),
  c({ id: "GDPR-6", frameworkId: "gdpr", area: "Accountability", title: "Data Protection Impact Assessments", description: "DPIAs are performed for high-risk processing activities.", owner: "Legal & Compliance", status: "Compliant" }),
  c({ id: "GDPR-7", frameworkId: "gdpr", area: "Lawfulness & Transparency", title: "Consent Management", description: "Consent is collected, recorded and withdrawable where consent is the lawful basis.", owner: "Marketing", status: "Compliant" }),
  c({ id: "GDPR-8", frameworkId: "gdpr", area: "Accountability", title: "Processor Agreements", description: "Data processing agreements are in place with all processors handling personal data.", owner: "Procurement", status: "Compliant" }),
  c({ id: "GDPR-9", frameworkId: "gdpr", area: "Data Subject Rights", title: "Retention and Erasure", description: "Personal data is retained only as long as necessary and securely erased thereafter.", owner: "IT", status: "Non-Compliant", notes: ["Legacy archive remediation in progress (see RISK-019)."] }),
  c({ id: "GDPR-10", frameworkId: "gdpr", area: "Security of Processing", title: "International Data Transfers", description: "Transfers outside the EEA rely on adequacy decisions or appropriate safeguards.", owner: "Legal & Compliance", status: "Compliant" }),
  c({ id: "GDPR-11", frameworkId: "gdpr", area: "Accountability", title: "Data Protection Officer & Governance", description: "Privacy governance roles and reporting lines are defined and operating.", owner: "Legal & Compliance", status: "Compliant" }),
  // NIST CSF
  c({ id: "NIST-GV1", frameworkId: "nist-csf", area: "Govern", title: "Cybersecurity Governance and Strategy", description: "Cybersecurity strategy, expectations and policy are established, communicated and monitored.", owner: "Security Team", status: "Compliant" }),
  c({ id: "NIST-ID1", frameworkId: "nist-csf", area: "Identify", title: "Asset Management", description: "Hardware, software, services and data are identified and managed consistent with their criticality.", owner: "IT", status: "Partial", notes: ["Cloud asset inventory automation being deployed."] }),
  c({ id: "NIST-ID2", frameworkId: "nist-csf", area: "Identify", title: "Risk Assessment", description: "Cybersecurity risk to the organisation is understood and prioritised.", owner: "Risk Team", status: "Compliant" }),
  c({ id: "NIST-PR1", frameworkId: "nist-csf", area: "Protect", title: "Identity Management and Access Control", description: "Access to assets is limited to authorised users, processes and devices.", owner: "IT", status: "Compliant" }),
  c({ id: "NIST-PR2", frameworkId: "nist-csf", area: "Protect", title: "Platform Security and Hardening", description: "Platforms are configured, hardened and patched to reduce attack surface.", owner: "IT", status: "Non-Compliant", notes: ["Endpoint patching SLA breaches under remediation (see RISK-020)."] }),
  c({ id: "NIST-DE1", frameworkId: "nist-csf", area: "Detect", title: "Continuous Monitoring", description: "Assets are monitored to find anomalies and potentially adverse events.", owner: "Security Operations", status: "Compliant" }),
  c({ id: "NIST-RS1", frameworkId: "nist-csf", area: "Respond", title: "Incident Response Management", description: "Responses to detected cybersecurity incidents are managed and coordinated.", owner: "Security Operations", status: "Compliant" }),
  c({ id: "NIST-RC1", frameworkId: "nist-csf", area: "Recover", title: "Incident Recovery Plan Execution", description: "Restoration activities are performed to ensure operational availability after incidents.", owner: "Engineering", status: "Non-Compliant", notes: ["Recovery exercises overdue for two critical services (see RISK-017)."] }),
  c({ id: "NIST-GV2", frameworkId: "nist-csf", area: "Govern", title: "Supply Chain Risk Management", description: "Cyber supply chain risk management processes are identified, established and monitored.", owner: "Procurement", status: "Compliant" }),
];

const v = (
  partial: Omit<
    Vendor,
    "categoryScores" | "documents" | "activity" | "linkedRisks" | "certifications"
  > &
    Partial<Vendor>,
): Vendor => ({
  certifications: [],
  categoryScores: [
    { category: "Cybersecurity", score: partial.score },
    { category: "Compliance", score: Math.min(100, partial.score + 6) },
    { category: "Financial Stability", score: Math.min(100, partial.score + 9) },
    { category: "Business Continuity", score: Math.max(20, partial.score - 8) },
    { category: "Privacy", score: Math.min(100, partial.score + 3) },
  ],
  documents: [],
  activity: [
    {
      id: `${partial.id}-a1`,
      date: partial.lastAssessment,
      title: "Assessment completed",
      detail: `Overall score ${partial.score}/100`,
      actor: "Sarah Mathew",
    },
  ],
  linkedRisks: [],
  ...partial,
});

export const SEED_VENDORS: Vendor[] = [
  v({
    id: "cloudnova",
    name: "CloudNova Technologies",
    service: "Cloud Infrastructure",
    businessOwner: "Arjun Nair",
    score: 82,
    level: "Low",
    assessmentStatus: "Completed",
    nextReview: "2027-03-01",
    lastAssessment: "2026-03-01",
    contractRenewal: "2027-06-30",
    criticality: "Critical",
    dataAccess: "Customer & production data",
    certifications: ["ISO 27001", "SOC 2 Type II", "GDPR DPA"],
    categoryScores: [
      { category: "Cybersecurity", score: 84 },
      { category: "Compliance", score: 88 },
      { category: "Financial Stability", score: 90 },
      { category: "Business Continuity", score: 74 },
      { category: "Privacy", score: 82 },
    ],
    documents: [
      { name: "CloudNova-SOC2-Report-2026.pdf", uploadedBy: "Divya Krishnan", date: "2026-02-20" },
      { name: "CloudNova-DPA-Signed.pdf", uploadedBy: "Meera Iyer", date: "2025-11-14" },
    ],
    activity: [
      { id: "cn-a1", date: "2026-03-01", title: "Annual assessment completed", detail: "Overall score 82/100 – Low Risk", actor: "Sarah Mathew" },
      { id: "cn-a2", date: "2026-02-20", title: "SOC 2 report received", actor: "Divya Krishnan" },
    ],
    linkedRisks: ["RISK-001", "RISK-004", "RISK-010"],
  }),
  v({
    id: "databridge",
    name: "DataBridge Solutions",
    service: "Data Processing",
    businessOwner: "Meera Iyer",
    score: 68,
    level: "Medium",
    assessmentStatus: "Pending Review",
    nextReview: "2026-10-15",
    lastAssessment: "2026-09-10",
    contractRenewal: "2027-01-31",
    criticality: "High",
    dataAccess: "Customer personal data",
    certifications: ["ISO 27001", "GDPR DPA"],
    categoryScores: [
      { category: "Cybersecurity", score: 72 },
      { category: "Compliance", score: 84 },
      { category: "Financial Stability", score: 88 },
      { category: "Business Continuity", score: 64 },
      { category: "Privacy", score: 79 },
    ],
    documents: [{ name: "DataBridge-Pen-Test-Summary.pdf", uploadedBy: "Rahul Menon", date: "2026-08-30" }],
    activity: [
      { id: "db-a1", date: "2026-09-10", title: "Assessment submitted", detail: "Awaiting risk team review", actor: "DataBridge Solutions" },
    ],
    linkedRisks: ["RISK-003"],
  }),
  v({
    id: "securepay",
    name: "SecurePay Systems",
    service: "Payment Processing",
    businessOwner: "Daniel Fernandez",
    score: 91,
    level: "Low",
    assessmentStatus: "Completed",
    nextReview: "2027-05-20",
    lastAssessment: "2026-05-20",
    contractRenewal: "2027-08-31",
    criticality: "High",
    dataAccess: "Payment transaction data",
    certifications: ["PCI DSS", "ISO 27001", "SOC 2 Type II"],
    linkedRisks: ["RISK-008"],
  }),
  v({
    id: "nexus",
    name: "Nexus Outsourcing",
    service: "Customer Support",
    businessOwner: "Divya Krishnan",
    score: 47,
    level: "High",
    assessmentStatus: "Pending Review",
    nextReview: "2026-10-06",
    lastAssessment: "2025-10-06",
    contractRenewal: "2026-12-31",
    criticality: "High",
    dataAccess: "Customer contact data",
    certifications: ["GDPR DPA"],
    categoryScores: [
      { category: "Cybersecurity", score: 41 },
      { category: "Compliance", score: 55 },
      { category: "Financial Stability", score: 62 },
      { category: "Business Continuity", score: 38 },
      { category: "Privacy", score: 49 },
    ],
    activity: [
      { id: "nx-a1", date: "2026-09-08", title: "Reassessment requested", detail: "Assessment expires in 14 days", actor: "Sarah Mathew" },
      { id: "nx-a2", date: "2025-10-06", title: "Assessment completed", detail: "Overall score 47/100 – High Risk", actor: "Sarah Mathew" },
    ],
    linkedRisks: ["RISK-002", "RISK-015"],
  }),
  v({ id: "cybershield", name: "CyberShield Ltd.", service: "Managed Security Services", businessOwner: "Rahul Menon", score: 74, level: "Medium", assessmentStatus: "Completed", nextReview: "2027-09-12", lastAssessment: "2026-09-12", contractRenewal: "2027-04-30", criticality: "High", dataAccess: "Security telemetry", certifications: ["ISO 27001", "SOC 2 Type II"] }),
  v({ id: "meridian", name: "Meridian Cloud Services", service: "Backup & Disaster Recovery", businessOwner: "Arjun Nair", score: 88, level: "Low", assessmentStatus: "Completed", nextReview: "2027-02-14", lastAssessment: "2026-02-14", contractRenewal: "2027-05-31", criticality: "High", dataAccess: "Encrypted backup data", certifications: ["ISO 27001", "SOC 2 Type II"], linkedRisks: ["RISK-010"] }),
  v({ id: "payrollpro", name: "PayrollPro Services", service: "Payroll Processing", businessOwner: "Priya Sharma", score: 85, level: "Low", assessmentStatus: "Completed", nextReview: "2027-01-25", lastAssessment: "2026-01-25", contractRenewal: "2027-03-31", criticality: "Medium", dataAccess: "Employee personal data", certifications: ["ISO 27001", "GDPR DPA"] }),
  v({ id: "legaledge", name: "LegalEdge Partners", service: "Legal Advisory", businessOwner: "Meera Iyer", score: 84, level: "Low", assessmentStatus: "Completed", nextReview: "2027-04-02", lastAssessment: "2026-04-02", contractRenewal: "2027-07-31", criticality: "Low", dataAccess: "Contract documents", certifications: ["GDPR DPA"] }),
  v({ id: "talenthub", name: "TalentHub HR Solutions", service: "Recruitment Platform", businessOwner: "Priya Sharma", score: 83, level: "Low", assessmentStatus: "Completed", nextReview: "2027-03-18", lastAssessment: "2026-03-18", contractRenewal: "2026-12-15", criticality: "Low", dataAccess: "Candidate personal data", certifications: ["ISO 27001"] }),
  v({ id: "netsecure", name: "NetSecure ISP", service: "Network Connectivity", businessOwner: "Arjun Nair", score: 86, level: "Low", assessmentStatus: "Completed", nextReview: "2027-06-09", lastAssessment: "2026-06-09", contractRenewal: "2028-01-31", criticality: "High", dataAccess: "Network traffic metadata", certifications: ["ISO 27001"] }),
  v({ id: "officespace", name: "OfficeSpace Facilities", service: "Facilities Management", businessOwner: "Wei Ling Tan", score: 90, level: "Low", assessmentStatus: "Completed", nextReview: "2027-05-05", lastAssessment: "2026-05-05", contractRenewal: "2027-09-30", criticality: "Low", dataAccess: "None", certifications: [] }),
  v({ id: "insurecorp", name: "InsureCorp Global", service: "Corporate Insurance", businessOwner: "Daniel Fernandez", score: 87, level: "Low", assessmentStatus: "Completed", nextReview: "2027-02-28", lastAssessment: "2026-02-28", contractRenewal: "2027-02-28", criticality: "Medium", dataAccess: "Financial summaries", certifications: ["ISO 27001"] }),
  v({ id: "devtools", name: "DevTools Inc.", service: "Development Tooling", businessOwner: "Vikram Rao", score: 77, level: "Medium", assessmentStatus: "In Progress", nextReview: "2026-11-08", lastAssessment: "2025-11-08", contractRenewal: "2027-01-15", criticality: "Medium", dataAccess: "Source code metadata", certifications: ["SOC 2 Type II"] }),
  v({ id: "marketreach", name: "MarketReach Digital", service: "Marketing Automation", businessOwner: "Ahmed Al Farsi", score: 71, level: "Medium", assessmentStatus: "Completed", nextReview: "2027-01-19", lastAssessment: "2026-01-19", contractRenewal: "2026-11-30", criticality: "Low", dataAccess: "Prospect contact data", certifications: ["GDPR DPA"] }),
  v({ id: "cloudprint", name: "CloudPrint Services", service: "Managed Print", businessOwner: "Wei Ling Tan", score: 66, level: "Medium", assessmentStatus: "Not Started", nextReview: "2026-10-30", lastAssessment: "2025-09-15", contractRenewal: "2027-03-15", criticality: "Low", dataAccess: "Document print queues", certifications: [] }),
  v({ id: "logitrans", name: "LogiTrans Couriers", service: "Logistics & Courier", businessOwner: "Divya Krishnan", score: 63, level: "Medium", assessmentStatus: "Not Started", nextReview: "2026-11-12", lastAssessment: "2025-08-20", contractRenewal: "2026-12-31", criticality: "Low", dataAccess: "Shipping addresses", certifications: [] }),
  v({ id: "quickfix", name: "QuickFix IT Services", service: "On-site IT Support", businessOwner: "Arjun Nair", score: 52, level: "High", assessmentStatus: "In Progress", nextReview: "2026-10-22", lastAssessment: "2025-10-22", contractRenewal: "2026-11-30", criticality: "Medium", dataAccess: "Endpoint admin access", certifications: [] }),
  v({ id: "datavault", name: "DataVault Archiving", service: "Records Archiving", businessOwner: "Meera Iyer", score: 55, level: "High", assessmentStatus: "Expiring Soon", nextReview: "2026-10-06", lastAssessment: "2025-10-01", contractRenewal: "2027-01-31", criticality: "Medium", dataAccess: "Archived customer records", certifications: ["GDPR DPA"], linkedRisks: ["RISK-019"] }),
];

const inc = (
  partial: Omit<
    Incident,
    "timeline" | "correctiveActions" | "linkedRisks" | "attachments" | "systemsAffected" | "rootCause" | "businessImpact"
  > &
    Partial<Incident>,
): Incident => ({
  businessImpact: "Limited operational impact; monitored by the incident response team.",
  systemsAffected: [],
  rootCause: "Under investigation.",
  timeline: [
    { id: `${partial.id}-t1`, date: partial.reportedDate, title: "Incident reported", actor: partial.reportedBy },
    { id: `${partial.id}-t2`, date: partial.reportedDate, title: "Triaged and assigned", detail: `Assigned to ${partial.assignedTo}`, actor: "Security Operations" },
  ],
  correctiveActions: [],
  linkedRisks: [],
  attachments: [],
  ...partial,
});

export const SEED_INCIDENTS: Incident[] = [
  inc({
    id: "INC-015",
    title: "Unauthorised USB storage device detected",
    description: "Endpoint monitoring flagged use of an unapproved USB storage device on a finance workstation.",
    category: "Security Incident",
    severity: "Low",
    reportedBy: "Endpoint Monitoring",
    assignedTo: "IT Security",
    status: "Triaged",
    reportedDate: "2026-09-18",
  }),
  inc({
    id: "INC-014",
    title: "Suspicious privileged login from unrecognised location",
    description:
      "A domain administrator account authenticated from an unrecognised network location outside business hours. The session was terminated and credentials rotated while investigation continues.",
    category: "Security Incident",
    severity: "Critical",
    reportedBy: "Security Operations",
    assignedTo: "Rahul Menon",
    status: "Investigating",
    reportedDate: "2026-09-15",
    businessImpact: "Potential unauthorised access to production administration plane. No confirmed data exfiltration to date.",
    systemsAffected: ["Active Directory", "Production Admin VPN"],
    rootCause: "Suspected credential compromise via phishing; forensic review in progress.",
    timeline: [
      { id: "i14-t1", date: "2026-09-15", title: "Incident reported", detail: "SIEM alert – anomalous privileged login", actor: "Security Operations" },
      { id: "i14-t2", date: "2026-09-15", title: "Triaged", detail: "Classified initially as High severity", actor: "Rahul Menon" },
      { id: "i14-t3", date: "2026-09-16", title: "Escalated to Critical", detail: "Privileged scope confirmed; executive notification issued", actor: "Sarah Mathew" },
      { id: "i14-t4", date: "2026-09-17", title: "Containment actions", detail: "Credentials rotated, conditional access tightened", actor: "IT Security" },
    ],
    correctiveActions: [
      { id: "i14-ca1", title: "Complete forensic review of affected account activity", owner: "Rahul Menon", dueDate: "2026-09-29", status: "In Progress" },
      { id: "i14-ca2", title: "Enforce phishing-resistant MFA for all privileged accounts", owner: "Arjun Nair", dueDate: "2026-10-10", status: "Not Started" },
    ],
    linkedRisks: ["RISK-007", "RISK-005"],
    attachments: [{ name: "SIEM-Alert-Export-INC014.pdf", uploadedBy: "Rahul Menon", date: "2026-09-15" }],
  }),
  inc({
    id: "INC-013",
    title: "Customer data accidentally shared with wrong recipient",
    description: "A support agent attached a report containing customer contact details to an email sent to the wrong customer.",
    category: "Data Privacy",
    severity: "High",
    reportedBy: "Customer Support",
    assignedTo: "Privacy Team",
    status: "Containment",
    reportedDate: "2026-09-12",
    businessImpact: "Personal data of 42 customer contacts disclosed to a single unintended recipient. Recall and deletion confirmation obtained.",
    systemsAffected: ["Support CRM", "Email"],
    rootCause: "Manual attachment process without recipient verification step.",
    correctiveActions: [
      { id: "i13-ca1", title: "Assess GDPR notification obligation", owner: "Meera Iyer", dueDate: "2026-09-20", status: "Completed" },
      { id: "i13-ca2", title: "Introduce DLP rule for bulk customer data in email", owner: "Rahul Menon", dueDate: "2026-10-15", status: "In Progress" },
    ],
    linkedRisks: ["RISK-003"],
  }),
  inc({
    id: "INC-012",
    title: "Production service outage – API gateway degradation",
    description: "A configuration rollout degraded API gateway performance, causing elevated error rates for 3 hours.",
    category: "Operational",
    severity: "Medium",
    reportedBy: "Engineering",
    assignedTo: "DevOps",
    status: "Resolved",
    reportedDate: "2026-09-08",
    businessImpact: "Elevated error rates for 3 hours affecting 12 enterprise customers. SLA credits issued to 2 customers.",
    systemsAffected: ["API Gateway", "Customer Portal"],
    rootCause: "Misconfigured rate-limit policy deployed without canary validation.",
    correctiveActions: [
      { id: "i12-ca1", title: "Mandate canary stage for gateway config changes", owner: "Vikram Rao", dueDate: "2026-09-30", status: "Completed" },
    ],
    linkedRisks: ["RISK-004"],
  }),
  inc({
    id: "INC-011",
    title: "Lost corporate laptop reported in transit",
    description: "An employee reported a corporate laptop lost during travel between Dubai and Bengaluru.",
    category: "Security Incident",
    severity: "Medium",
    reportedBy: "Employee Self-Service",
    assignedTo: "IT Security",
    status: "Remediation",
    reportedDate: "2026-09-05",
    businessImpact: "Device was encrypted and remotely wiped. No evidence of data access.",
    systemsAffected: ["Endpoint Fleet"],
    rootCause: "Device misplaced during airport transfer.",
    correctiveActions: [
      { id: "i11-ca1", title: "Confirm remote wipe attestation", owner: "IT Security", dueDate: "2026-09-25", status: "In Progress" },
    ],
  }),
  inc({
    id: "INC-010",
    title: "Phishing campaign targeting finance department",
    description: "Multiple finance staff received invoice-themed phishing emails impersonating a known supplier.",
    category: "Security Incident",
    severity: "High",
    reportedBy: "Finance Team",
    assignedTo: "Rahul Menon",
    status: "Investigating",
    reportedDate: "2026-09-03",
    businessImpact: "Two users clicked the link; no credential compromise confirmed. Mail rules updated.",
    systemsAffected: ["Email", "Finance Workstations"],
    rootCause: "Supplier impersonation using lookalike domain.",
    correctiveActions: [
      { id: "i10-ca1", title: "Block lookalike domain and report for takedown", owner: "IT Security", dueDate: "2026-09-22", status: "Completed" },
      { id: "i10-ca2", title: "Targeted phishing refresher for finance staff", owner: "Priya Sharma", dueDate: "2026-10-05", status: "In Progress" },
    ],
    linkedRisks: ["RISK-005", "RISK-008"],
  }),
  inc({
    id: "INC-009",
    title: "Malware detection on marketing workstation",
    description: "EDR detected and quarantined a trojan downloader on a marketing workstation following a malicious document download.",
    category: "Security Incident",
    severity: "Medium",
    reportedBy: "Endpoint Monitoring",
    assignedTo: "IT Security",
    status: "Investigating",
    reportedDate: "2026-08-29",
    businessImpact: "Malware quarantined before execution. Workstation reimaged as a precaution.",
    systemsAffected: ["Marketing Workstation APX-1142"],
    rootCause: "Malicious macro document from personal webmail.",
    correctiveActions: [
      { id: "i9-ca1", title: "Restrict personal webmail on corporate devices", owner: "Arjun Nair", dueDate: "2026-10-01", status: "In Progress" },
    ],
    linkedRisks: ["RISK-001"],
  }),
  inc({
    id: "INC-008",
    title: "Vendor SLA breach – support platform outage",
    description: "Nexus Outsourcing's support platform was unavailable for 6 hours, breaching the contracted 99.5% availability SLA.",
    category: "Third Party",
    severity: "Low",
    reportedBy: "Operations",
    assignedTo: "Divya Krishnan",
    status: "Investigating",
    reportedDate: "2026-08-25",
    businessImpact: "Customer support response times degraded for one business day.",
    systemsAffected: ["Outsourced Support Platform"],
    rootCause: "Vendor data centre failover failure; RCA requested from vendor.",
    linkedRisks: ["RISK-015", "RISK-002"],
  }),
  inc({
    id: "INC-007",
    title: "Email spam wave bypassing filters",
    description: "A short-lived spam wave bypassed email filtering rules before updated signatures were applied.",
    category: "Security Incident",
    severity: "Low",
    reportedBy: "IT Helpdesk",
    assignedTo: "IT Security",
    status: "Resolved",
    reportedDate: "2026-09-02",
    rootCause: "Delayed filter signature update.",
  }),
  inc({
    id: "INC-006",
    title: "Data centre cooling alert – Bengaluru server room",
    description: "Temperature threshold exceeded in the Bengaluru server room due to a failed CRAC unit. Redundant cooling engaged.",
    category: "Operational",
    severity: "Low",
    reportedBy: "Facilities",
    assignedTo: "Facilities",
    status: "Resolved",
    reportedDate: "2026-09-01",
    rootCause: "CRAC unit compressor failure; unit replaced.",
  }),
];

export const RISK_TREND = [
  { month: "Apr", score: 72 },
  { month: "May", score: 70 },
  { month: "Jun", score: 69 },
  { month: "Jul", score: 67 },
  { month: "Aug", score: 66 },
  { month: "Sep", score: 64 },
];

export const OVERALL_RISK_SCORE = 64;
export const CONTROLS_IMPLEMENTED = 86;

export const SEED_NOTIFICATIONS: Notification[] = [
  { id: "n1", message: "RISK-023 requires review – brand impersonation risk review is due.", date: "2026-09-21", href: "/risks/RISK-023", read: false },
  { id: "n2", message: "Vendor assessment for Nexus Outsourcing expires in 14 days.", date: "2026-09-20", href: "/vendors/nexus", read: false },
  { id: "n3", message: "ISO 27001 evidence required for Control A.8.12 (Data Leakage Prevention).", date: "2026-09-19", href: "/compliance/iso-27001", read: false },
  { id: "n4", message: "INC-014 has been escalated to Critical severity.", date: "2026-09-16", href: "/incidents/INC-014", read: false },
];

export const SEED_ACTIVITY: ActivityItem[] = [
  { id: "a1", message: "Vendor CyberShield Ltd. completed its security assessment.", date: "2026-09-12", href: "/vendors/cybershield" },
  { id: "a2", message: "RISK-023 assigned to IT Security.", date: "2026-09-12", href: "/risks/RISK-023" },
  { id: "a3", message: "ISO 27001 Control A.8.12 marked as non-compliant pending DLP rollout.", date: "2026-09-10", href: "/compliance/iso-27001" },
  { id: "a4", message: "Incident INC-014 escalated to Critical severity.", date: "2026-09-16", href: "/incidents/INC-014" },
  { id: "a5", message: "ISO 27001 Control A.6.3 evidence updated (Q3 awareness completion).", date: "2026-09-01", href: "/compliance/iso-27001" },
];

export const COMPLIANCE_QUESTIONS: AssessmentQuestion[] = [
  { id: "cq1", section: "Governance", text: "Does the organisation maintain an approved information security policy?", mappedControl: "A.5.1" },
  { id: "cq2", section: "Governance", text: "Are information security roles and responsibilities formally assigned?", mappedControl: "A.5.1" },
  { id: "cq3", section: "Access Control", text: "Are privileged user accounts reviewed periodically?", mappedControl: "A.8.2" },
  { id: "cq4", section: "Access Control", text: "Is MFA enabled for critical systems?", mappedControl: "A.5.15" },
  { id: "cq5", section: "Access Control", text: "Are access rights revoked promptly on termination?", mappedControl: "A.6.5" },
  { id: "cq6", section: "Operations", text: "Are backups performed and restoration tested regularly?", mappedControl: "A.8.13" },
  { id: "cq7", section: "Operations", text: "Is anti-malware protection deployed across all endpoints?", mappedControl: "A.8.7" },
  { id: "cq8", section: "Operations", text: "Are systems and applications monitored for anomalous activity?", mappedControl: "A.8.16" },
  { id: "cq9", section: "Data Protection", text: "Are data leakage prevention measures applied to sensitive information?", mappedControl: "A.8.12" },
  { id: "cq10", section: "Data Protection", text: "Are data retention and disposal requirements defined and enforced?", mappedControl: "A.7.10" },
  { id: "cq11", section: "People", text: "Do all employees complete security awareness training at least annually?", mappedControl: "A.6.3" },
  { id: "cq12", section: "People", text: "Are background checks performed before employment?", mappedControl: "A.6.1" },
];

export const VENDOR_QUESTIONS: AssessmentQuestion[] = [
  { id: "vq1", section: "Company Information", text: "Has the vendor provided complete and current company and ownership information?" },
  { id: "vq2", section: "Financial Stability", text: "Has the vendor demonstrated financial stability for the last two financial years?" },
  { id: "vq3", section: "Cybersecurity", text: "Does the vendor hold ISO 27001 certification?" },
  { id: "vq4", section: "Cybersecurity", text: "Does the vendor conduct annual penetration tests?" },
  { id: "vq5", section: "Cybersecurity", text: "Is MFA enabled for privileged users?" },
  { id: "vq6", section: "Cybersecurity", text: "Has the vendor experienced a security breach during the last 24 months?" },
  { id: "vq7", section: "Data Privacy", text: "Does the vendor encrypt sensitive information at rest?" },
  { id: "vq8", section: "Data Privacy", text: "Is a signed data processing agreement (DPA) in place?" },
  { id: "vq9", section: "Business Continuity", text: "Does the vendor maintain an incident response plan?" },
  { id: "vq10", section: "Business Continuity", text: "Are business continuity and disaster recovery plans tested annually?" },
  { id: "vq11", section: "Compliance", text: "Does the vendor comply with applicable regulatory requirements for the service provided?" },
  { id: "vq12", section: "Vendor Management", text: "Does the vendor manage the security of its own sub-contractors?" },
  { id: "vq13", section: "Contractual Controls", text: "Do contracts include security, audit and termination-assistance clauses?" },
  { id: "vq14", section: "Contractual Controls", text: "Are service levels and remedies clearly defined in the contract?" },
];

export const REPORTS = [
  { id: "rep-1", name: "Executive GRC Summary", description: "Board-level overview of risk posture, compliance status and key exposures.", frequency: "Monthly", lastGenerated: "2026-09-01", format: "PDF" },
  { id: "rep-2", name: "Enterprise Risk Report", description: "Full risk register analysis with movement, treatment progress and heatmap.", frequency: "Monthly", lastGenerated: "2026-09-01", format: "PDF" },
  { id: "rep-3", name: "Compliance Status Report", description: "Framework-by-framework control status, gaps and evidence readiness.", frequency: "Monthly", lastGenerated: "2026-08-28", format: "PDF" },
  { id: "rep-4", name: "ISO 27001 Assessment", description: "Detailed Annex A control assessment for certification readiness.", frequency: "Quarterly", lastGenerated: "2026-07-15", format: "PDF" },
  { id: "rep-5", name: "Third-Party Risk Report", description: "Vendor portfolio risk distribution, assessment status and expiring reviews.", frequency: "Monthly", lastGenerated: "2026-09-05", format: "PDF" },
  { id: "rep-6", name: "Incident Summary", description: "Incident volumes, severity trends, response times and open actions.", frequency: "Monthly", lastGenerated: "2026-09-02", format: "PDF" },
  { id: "rep-7", name: "Quarterly Risk Review", description: "Quarter-end review pack for the risk committee with recommendations.", frequency: "Quarterly", lastGenerated: "2026-06-30", format: "PDF" },
];

export const SETTINGS_USERS = [
  { name: "Sarah Mathew", email: "sarah.mathew@apextech.example", role: "Risk Manager", department: "Legal & Compliance", status: "Active" },
  { name: "Arjun Nair", email: "arjun.nair@apextech.example", role: "Department Owner", department: "IT", status: "Active" },
  { name: "Rahul Menon", email: "rahul.menon@apextech.example", role: "Risk Manager", department: "IT Security", status: "Active" },
  { name: "Meera Iyer", email: "meera.iyer@apextech.example", role: "Compliance Manager", department: "Legal & Compliance", status: "Active" },
  { name: "Divya Krishnan", email: "divya.krishnan@apextech.example", role: "Department Owner", department: "Procurement", status: "Active" },
  { name: "Priya Sharma", email: "priya.sharma@apextech.example", role: "Department Owner", department: "HR", status: "Active" },
  { name: "Daniel Fernandez", email: "daniel.fernandez@apextech.example", role: "Department Owner", department: "Finance", status: "Active" },
  { name: "Ahmed Al Farsi", email: "ahmed.alfarsi@apextech.example", role: "Viewer", department: "Strategy", status: "Invited" },
  { name: "James Wong", email: "james.wong@apextech.example", role: "Auditor", department: "External", status: "Active" },
  { name: "Anita Desai", email: "anita.desai@apextech.example", role: "Administrator", department: "IT", status: "Active" },
];

export const ROLES = [
  { name: "Administrator", description: "Full platform configuration and user management." },
  { name: "Risk Manager", description: "Manage the risk register, assessments and treatment plans." },
  { name: "Compliance Manager", description: "Manage frameworks, controls and evidence." },
  { name: "Auditor", description: "Read-only access to records and evidence for audit purposes." },
  { name: "Department Owner", description: "Manage risks and actions assigned to their department." },
  { name: "Viewer", description: "Read-only access to dashboards and reports." },
];

export const DEPARTMENTS = [
  "IT",
  "IT Security",
  "Engineering",
  "Operations",
  "Finance",
  "Legal & Compliance",
  "HR",
  "Procurement",
  "Facilities",
  "Marketing",
];

export const RISK_CATEGORIES = [
  "Cybersecurity",
  "Operational",
  "Financial",
  "Compliance",
  "Strategic",
  "Third Party",
  "Data Privacy",
  "Business Continuity",
];

export const OWNERS = [
  "Arjun Nair",
  "Rahul Menon",
  "Meera Iyer",
  "Divya Krishnan",
  "Priya Sharma",
  "Daniel Fernandez",
  "Vikram Rao",
  "Wei Ling Tan",
  "Ahmed Al Farsi",
  "Sarah Mathew",
];
